---
version: '2'
services:
  cache:
    build: ./redis
    ports:
      - "6379:6379"
  message:
    build: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  monitor:
    build: ./sensu
    ports:
      - "4567:4567"
